import { chromium } from '../../../../packages/app/node_modules/@playwright/test/index.mjs'
const browser = await chromium.launch({headless:true, executablePath:'/Users/leanbot/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'})
const page=await browser.newPage()
page.on('pageerror',e=>console.log('PAGEERROR',e.message))
page.on('request',r=>{if(r.url().includes(':4150')) console.log('REQ',r.url())})
page.on('requestfailed',r=>console.log('FAIL',r.url(),r.failure()))
page.on('console',m=>{if(m.type()==='error')console.log('ERROR',m.text())})
await page.goto('http://127.0.0.1:4450', {waitUntil:'domcontentloaded',timeout:60000})
console.log('LOADED',await page.locator('body').innerText())
await page.getByRole('button',{name:/^(Add project|Ajouter un projet)$/,exact:true}).waitFor({timeout:60000}).catch(async e=>{console.log('TIMEOUT', await page.locator('body').innerText());throw e})
console.log(await page.locator('body').innerText())
await page.getByRole('button',{name:/^(Add project|Ajouter un projet)$/,exact:true}).click()
console.log(await page.getByRole('dialog').innerText())
await browser.close()
