import { chromium, expect } from '../../../../packages/app/node_modules/@playwright/test/index.mjs'
import { existsSync, writeFileSync } from 'node:fs'
const root='/Users/leanbot/Documents/40_Daidalon/features/10-product-ui'
const evidence=root+'/.project/tasks/DA10-002-ouverture-projet-explicite/evidence'
const empty=evidence+'/runtime/empty'
const browser=await chromium.launch({headless:true,executablePath:'/Users/leanbot/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'})
const page=await browser.newPage()
page.setDefaultTimeout(60000)
const requests=[]
const errors=[]
page.on('request',r=>{if(r.url().includes(':4150'))requests.push({method:r.method(),url:r.url()})})
page.on('pageerror',e=>errors.push(e.message))
try {
  expect(existsSync(empty+'/.git')).toBe(false)
  await page.goto('http://127.0.0.1:4450',{waitUntil:'domcontentloaded'})
  const add=page.locator('[data-action="home-add-project-row"]')
  await expect(add).toBeEnabled()
  await add.click()
  const dialog=page.getByRole('dialog')
  const input=dialog.getByRole('combobox')
  const confirm=dialog.getByRole('button',{name:/^(Select folder|Sélectionner le dossier)$/})
  await input.fill(empty)
  await input.press('Enter')
  await expect(confirm).toBeEnabled({timeout:60000})
  await expect(dialog.locator('[data-component="project-context"]')).toContainText(empty)
  await input.fill(empty+'/missing')
  await expect(confirm).toBeDisabled()
  await input.press('Enter')
  await expect(dialog).toContainText('Folder is missing. Existing history is preserved.')
  await expect(confirm).toBeDisabled()
  await dialog.getByRole('button',{name:/^(Cancel|Annuler)$/}).click()
  await expect(dialog).toBeHidden()
  expect(existsSync(empty+'/.git')).toBe(false)
  await add.click()
  await input.fill(empty)
  await input.press('Enter')
  await expect(confirm).toBeEnabled({timeout:60000})
  await confirm.click()
  await expect(dialog).toBeHidden()
  const panel=page.locator('[data-component="project-context"]')
  await expect(panel).toContainText('Folder is available')
  await expect(panel).toContainText(empty)
  await panel.getByText('Project context details',{exact:true}).click()
  await expect(panel).toContainText('10-product-ui')
  await page.getByLabel('Base reference (optional)').fill('HEAD')
  await page.getByRole('button',{name:'Refresh context',exact:true}).click()
  await expect(panel).toContainText('Base resolved')
  await expect(panel).toContainText('702bf7dcd7468638c17fd95b110deb38bd253e9a')
  await page.route('**/global/context?**',route=>route.fulfill({status:401,body:'{}',contentType:'application/json'}))
  await page.getByRole('button',{name:'Refresh context',exact:true}).click()
  await expect(panel).toContainText('Authentication failed.')
  await expect(panel).not.toContainText('Base resolved')
  await page.unroute('**/global/context?**')
  await page.route('**/global/context?**',route=>route.abort('connectionfailed'))
  await page.getByRole('button',{name:'Refresh context',exact:true}).click()
  await expect(panel).toContainText('Could not reach this server.')
  await page.unroute('**/global/context?**')
  await page.getByRole('button',{name:'Refresh context',exact:true}).click()
  await expect(panel).toContainText('Folder is available')
  expect(existsSync(empty+'/.git')).toBe(false)
  expect(requests.filter(r=>r.method==='POST' && /project.*git/.test(r.url))).toEqual([])
  expect(errors).toEqual([])
  writeFileSync(evidence+'/browser-smoke.json',JSON.stringify({pass:true,url:page.url(),empty,no_dot_git:true,requests,pageerrors:errors,auth_network:'injected browser transport failures; real context response on recovery'},null,2))
  console.log('PASS: navigate, edit, absent, cancel, empty open, branch/HEAD/base, auth/network/recovery; no .git/initGit')
} catch(error) {
  writeFileSync(evidence+'/browser-smoke-failure.txt',await page.locator('body').innerText())
  throw error
} finally {await browser.close()}
